test project:
    nix develop --command sh -c "cd {{project}} && mix test"

test-all:
    #!/usr/bin/env bash
    set -e
    for dir in */; do
        if [ -f "$dir/mix.exs" ]; then
            echo "Testing ${dir%/}..."
            nix develop --command sh -c "cd $dir && mix test"
        fi
    done

