test project:
    nix develop --command sh -c "cd {{project}} && cargo test"

test-all:
    #!/usr/bin/env bash
    set -e
    for dir in */; do
        if [ -f "$dir/Cargo.toml" ]; then
            echo "Testing ${dir%/}..."
            nix develop --command sh -c "cd $dir && cargo test"
        fi
    done

